"""empty message

Revision ID: e42be0195e6a
Revises: e7415208df49
Create Date: 2020-01-17 01:42:06.758950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e42be0195e6a'
down_revision = 'e7415208df49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('manufacturer', sa.String(length=30), nullable=True),
    sa.Column('part_no', sa.String(length=30), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['station_code'], ['station.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_station_code'), 'sensor', ['station_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_station_code'), table_name='sensor')
    op.drop_table('sensor')
    # ### end Alembic commands ###
